
//REDUCERS
export const SERVICE_REDUCER = "SERVICE_REDUCER"
export const USER_REDUCER = "USER_REDUCER"
export const REQUEST_REDUCER = "REQUEST_REDUCER"

//SERVICES
export const ALL_SERVICES = "ALL_SERVICES"
export const USER_SERVICES = "USER_SERVICES"
export const CREATE_SERVICE = "CREATE_SERVICE"


//USERS
export const ALL_PROVIDERS = "ALL_PROVIDERS"


//REQUESTS
export const CREATE_REQUEST = "CREATE_REQUEST"
export const UPDATE_REQUEST = "UPDATE_REQUEST"
export const PROVIDER_REQUESTS = "PROVIDER_REQUESTS"
export const ALL_REQUESTS = "ALL_REQUESTS"
